// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDH_aV4QB_w78QagxeJtbhLrtqwExORGug',
    appId: '1:605365391186:web:dc328176abb5f3c7c1b48b',
    messagingSenderId: '605365391186',
    projectId: 'snapfix-e4329',
    authDomain: 'snapfix-e4329.firebaseapp.com',
    storageBucket: 'snapfix-e4329.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-GSHQHlIjTi5mVahQAU2kAA92iRAYq_o',
    appId: '1:605365391186:android:0db5d5550136d2eec1b48b',
    messagingSenderId: '605365391186',
    projectId: 'snapfix-e4329',
    storageBucket: 'snapfix-e4329.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCq1m09KtLnIAsLogMxTR1pJHmecE1bUuo',
    appId: '1:605365391186:ios:fb8d864b0077904cc1b48b',
    messagingSenderId: '605365391186',
    projectId: 'snapfix-e4329',
    storageBucket: 'snapfix-e4329.firebasestorage.app',
    iosBundleId: 'yusvan.damagereports',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCq1m09KtLnIAsLogMxTR1pJHmecE1bUuo',
    appId: '1:605365391186:ios:fb8d864b0077904cc1b48b',
    messagingSenderId: '605365391186',
    projectId: 'snapfix-e4329',
    storageBucket: 'snapfix-e4329.firebasestorage.app',
    iosBundleId: 'yusvan.damagereports',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDH_aV4QB_w78QagxeJtbhLrtqwExORGug',
    appId: '1:605365391186:web:ca610ea9c04061eec1b48b',
    messagingSenderId: '605365391186',
    projectId: 'snapfix-e4329',
    authDomain: 'snapfix-e4329.firebaseapp.com',
    storageBucket: 'snapfix-e4329.firebasestorage.app',
  );
}
