import 'package:damagereports/data/model/response/kerusakan_admin_response_model.dart';
import 'package:flutter/material.dart';
import 'package:intl/intl.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';

class KerusakanPdfService {
  static Future<void> export({
    required List<KerusakanAdmin> data,
    required String project,
    required String status,
    required DateTimeRange? dateRange,
  }) async {
    final pdf = pw.Document();

    final dateFormat = DateFormat('dd-MM-yyyy');

    String tanggal;

    if (dateRange == null) {
      tanggal = "7 Hari Terakhir";
    } else {
      tanggal =
          "${dateFormat.format(dateRange.start)} s/d ${dateFormat.format(dateRange.end)}";
    }

    final totalPending =
        data.where((e) => e.status.toLowerCase() == "pending").length;

    final totalPerbaikan =
        data.where((e) => e.status.toLowerCase() == "diperbaiki").length;

    final totalSelesai =
        data.where((e) => e.status.toLowerCase() == "selesai").length;
    
    final Map<String, pw.ImageProvider> imageCache = {};

    for (final item in data) {
      if (item.fotoKerusakan != null &&
          item.fotoKerusakan!.isNotEmpty) {
        try {
          imageCache[item.fotoKerusakan!] =
              await networkImage(item.fotoKerusakan!);
        } catch (_) {}
      }

      if (item.fotoPerbaikan != null &&
          item.fotoPerbaikan!.isNotEmpty) {
        try {
          imageCache[item.fotoPerbaikan!] =
              await networkImage(item.fotoPerbaikan!);
        } catch (_) {}
      }
    }

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4.landscape,

        margin: const pw.EdgeInsets.all(20),

        footer: (context) {
          return pw.Container(
            alignment: pw.Alignment.centerRight,

            margin: const pw.EdgeInsets.only(top: 10),

            child: pw.Text(
              "Generated by SnapFix | Halaman ${context.pageNumber} dari ${context.pagesCount}",

              style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey700),
            ),
          );
        },

        build: (context) {
          return [
            //---------------------------------------
            // HEADER
            //---------------------------------------
            pw.Center(
              child: pw.Text(
                "SNAPFIX",
                style: pw.TextStyle(
                  fontSize: 28,
                  fontWeight: pw.FontWeight.bold,
                  color: PdfColors.blue900,
                ),
              ),
            ),

            pw.SizedBox(height: 5),

            pw.Center(
              child: pw.Text(
                "LAPORAN DATA KERUSAKAN",

                style: pw.TextStyle(
                  fontSize: 18,
                  fontWeight: pw.FontWeight.bold,
                  color: PdfColors.black,
                ),
              ),
            ),

            pw.Divider(),
            pw.Container(height: 3, color: PdfColors.blue900),

            pw.SizedBox(height: 15),

            //---------------------------------------
            // FILTER
            //---------------------------------------
            pw.Row(
              children: [
                pw.Expanded(
                  child: pw.Column(
                    crossAxisAlignment: pw.CrossAxisAlignment.start,
                    children: [
                      pw.Text(
                        "Project",
                        style: pw.TextStyle(fontWeight: pw.FontWeight.bold),
                      ),

                      pw.Text(project),
                    ],
                  ),
                ),

                pw.Expanded(
                  child: pw.Column(
                    crossAxisAlignment: pw.CrossAxisAlignment.start,
                    children: [
                      pw.Text(
                        "Status",
                        style: pw.TextStyle(fontWeight: pw.FontWeight.bold),
                      ),

                      pw.Text(status),
                    ],
                  ),
                ),

                pw.Expanded(
                  child: pw.Column(
                    crossAxisAlignment: pw.CrossAxisAlignment.start,
                    children: [
                      pw.Text(
                        "Tanggal",
                        style: pw.TextStyle(fontWeight: pw.FontWeight.bold),
                      ),

                      pw.Text(tanggal),
                    ],
                  ),
                ),
              ],
            ),

            pw.SizedBox(height: 20),

            //---------------------------------------
            // STATISTIK
            //---------------------------------------
            pw.Container(
              padding: const pw.EdgeInsets.all(12),

              decoration: pw.BoxDecoration(
                border: pw.Border.all(color: PdfColors.grey),
              ),

              child: pw.Row(
                mainAxisAlignment: pw.MainAxisAlignment.spaceEvenly,

                children: [
                  _buildBox("Total", "${data.length}", PdfColors.orange),

                  _buildBox("Pending", "$totalPending", PdfColors.red),

                  _buildBox("Diperbaiki", "$totalPerbaikan", PdfColors.blue),

                  _buildBox("Selesai", "$totalSelesai", PdfColors.green),
                ],
              ),
            ),

            pw.SizedBox(height: 20),

            pw.Table(
              border: pw.TableBorder.all(color: PdfColors.grey600, width: 0.5),
              columnWidths: {
                0: const pw.FixedColumnWidth(30),
                1: const pw.FixedColumnWidth(80),
                2: const pw.FixedColumnWidth(80),
                3: const pw.FixedColumnWidth(80),
                4: const pw.FixedColumnWidth(70),
                5: const pw.FixedColumnWidth(70),
                6: const pw.FixedColumnWidth(120),
                7: const pw.FixedColumnWidth(70),
                8: const pw.FixedColumnWidth(70),
              },
              children: [
                //================ HEADER ==================
                pw.TableRow(
                  decoration: const pw.BoxDecoration(color: PdfColors.blue900),
                  children: [
                    _header("No"),
                    _header("Fasilitas"),
                    _header("Lokasi"),
                    _header("Pelapor"),
                    _header("Tanggal"),
                    _header("Status"),
                    _header("Deskripsi"),
                    _header("Foto Kerusakan"),
                    _header("Foto Perbaikan"),
                  ],
                ),

                //================ DATA ==================
                ...List.generate(data.length, (index) {
                  final item = data[index];

                  return pw.TableRow(
                    children: [
                      _cell("${index + 1}"),

                      _cell(item.fasilitas ?? "-"),

                      _cell(item.lokasi ?? "-"),

                      _cell(item.user ?? "-"),

                      _cell(
                        item.tanggal == null
                            ? "-"
                            : dateFormat.format(DateTime.parse(item.tanggal!)),
                      ),

                      _cell(item.status),

                      _cell(item.deskripsi),

                      //---------------- FOTO KERUSAKAN ----------------
                      pw.Container(
                        height: 70,
                        alignment: pw.Alignment.center,
                        padding: const pw.EdgeInsets.all(3),
                        child:
                            item.fotoKerusakan != null &&
                                    imageCache.containsKey(item.fotoKerusakan)
                                ? pw.Image(
                                  imageCache[item.fotoKerusakan!]!,
                                  fit: pw.BoxFit.contain,
                                )
                                : pw.Text("-"),
                      ),

                      //---------------- FOTO PERBAIKAN ----------------
                      pw.Container(
                        height: 70,
                        alignment: pw.Alignment.center,
                        padding: const pw.EdgeInsets.all(3),
                        child:
                            item.fotoPerbaikan != null &&
                                    imageCache.containsKey(item.fotoPerbaikan)
                                ? pw.Image(
                                  imageCache[item.fotoPerbaikan!]!,
                                  fit: pw.BoxFit.contain,
                                )
                                : pw.Text("-"),
                      ),
                    ],
                  );
                }),
              ],
            ),
            pw.SizedBox(height: 20),

            pw.Align(
              alignment: pw.Alignment.centerRight,

              child: pw.Text(
                "Dicetak : ${dateFormat.format(DateTime.now())}",

                style: const pw.TextStyle(fontSize: 10),
              ),
            ),
          ];
        },
      ),
    );

    await Printing.layoutPdf(onLayout: (format) async => pdf.save());
  }

  static pw.Widget _buildBox(String title, String value, PdfColor color) {
    return pw.Container(
      width: 120,

      padding: const pw.EdgeInsets.all(10),

      decoration: pw.BoxDecoration(
        color: color,

        borderRadius: pw.BorderRadius.circular(5),
      ),

      child: pw.Column(
        children: [
          pw.Text(
            title,

            style: pw.TextStyle(
              color: PdfColors.white,
              fontWeight: pw.FontWeight.bold,
            ),
          ),

          pw.SizedBox(height: 5),

          pw.Text(
            value,

            style: pw.TextStyle(
              color: PdfColors.white,
              fontWeight: pw.FontWeight.bold,
              fontSize: 20,
            ),
          ),
        ],
      ),
    );
  }

  static pw.Widget _header(String text) {
    return pw.Container(
      padding: const pw.EdgeInsets.all(5),
      alignment: pw.Alignment.center,
      color: PdfColors.blue900,
      child: pw.Text(
        text,
        textAlign: pw.TextAlign.center,
        style: pw.TextStyle(
          color: PdfColors.white,
          fontWeight: pw.FontWeight.bold,
          fontSize: 10,
        ),
      ),
    );
  }

  static pw.Widget _cell(String text) {
    return pw.Container(
      padding: const pw.EdgeInsets.all(5),
      alignment: pw.Alignment.centerLeft,
      child: pw.Text(
        text,
        style: const pw.TextStyle(
          fontSize: 9,
        ),
      ),
    );
  }
}
